""C:\Users\jl\OneDrive\Python\panoramic219\logs\python.exe"" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
Imagen HD seleccionada: SanVicentedelaBarquera.jpg
Imagen LD correspondiente encontrada: SanVicentedelaBarquera.jpg

--- Moviendo archivos ---

--- Resultado ---
HD movida a: C:\Users\jl\OneDrive\Python\panoramic219\hd\SanVicentedelaBarquera.jpg
LD movida a: C:\Users\jl\OneDrive\Python\panoramic219\ld\SanVicentedelaBarquera.jpg
